#!/bin/sh
#
#	/sbin/ifup-local
#
# version 0.98beta10
#
# Script to be run when an interface is enabled
#
#		** NOTE **
# Bastille may replace this script; please use 
# /sbin/ifup-local.pre-bastille for your local 
# script needs
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License, version 2, under which this file is licensed, for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Run the local ifup-local script
if [ -x /sbin/ifup-local.pre-bastille ]; then
	echo "running the original ifup-local script"
	/sbin/ifup-local.pre-bastille "${1}"
fi

# Reset the Bastille firewall
if [ -x /sbin/bastille-firewall-reset ]; then
	echo "resetting the Bastille firewall ruleset"
	/sbin/bastille-firewall-reset "${1}"
fi

